services:
  - type: web
    name: dj-drop-factory
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DARAJA_ENV
        value: sandbox
      - key: DARAJA_CONSUMER_KEY
        value: 7QPUZLBKANxkoI0D63vBXIY8NgwtVOg3hBZfoad6hfKGcIUK
      - key: DARAJA_CONSUMER_SECRET
        value: JiCV8ho34x5KCvDcI228dGvfOshdiHqWCmYUoSLuiHVQNHUfDJGOkUIXIcP3NGGw
      - key: DARAJA_PASSKEY
        value: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      - key: BASE_URL
        value: https://your-app-name.onrender.com   # <-- CHANGE ME
    healthCheckPath: /health
